# mouse mode
set -g mouse on

# unbind original h and v split
unbind "'"
unbind ";"

bind "'" split-window -c "#{pane_current_path}"
bind ";" split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# superior vim bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g pane-border-status top
set -g pane-border-format ''

set-option -g renumber-windows on
set-option -g detach-on-destroy off

set -g prefix C-b
bind-key -n C-v send-prefix

# status bar colors
set -g default-terminal "screen-256color"
set -g status-bg colour99
set -g status-fg white

set-option -g status-interval 1
set -g pane-border-format " #{pane_index} #{pane_current_command} — #{pane_current_path} "

set -g status-left ''
set -g status-right ''

set -g status-interval 5
set -g status-right-length 128
set -g status-right "#(~/.scripts/sysstat.sh)"

set -g status 2
set -g status-format[1] '#[bg=#1e1e2e,fill=#1e1e2e,align=left]#(~/.tmux/session-list.sh "#{session_name}")#[align=right]#[fg=white,bright,bg=#1e1e2e]#H %Y-%m-%d %H:%M#[bg=#1e1e2e]'

# select windows quickly
bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5

# switch sessions quickly
bind -n M-0 switch-client -n
bind -n M-9 switch-client -p

# switch panes quickly
bind -n M-S-Tab select-pane -t :.-
bind -n M-Tab select-pane -t :.+

# new pane quickly
bind -n M-c new-window -c "#{pane_current_path}"

# split pane quickly
bind -n "M-'" split-window -c "#{pane_current_path}"
bind -n "M-;" split-window -h -c "#{pane_current_path}"
