# mouse mode
set -g mouse on

# unbind original h and v split
unbind "'"
unbind ";"

bind "'" split-window -c "#{pane_current_path}"
bind ";" split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# superior vim bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set-option -g renumber-windows on
set-option -g detach-on-destroy off

set -g prefix C-b
bind-key -n C-v send-prefix

# status bar colors
set -g default-terminal "screen-256color"
set -g status-bg colour99
set -g status-fg white

set-option -g status-interval 1

set -g status-left ''
set -g status-right ''

set -g status 2
set -g status-format[1] '#[align=left]#(~/.tmux/session-list.sh "#{session_name}")#[align=right]#[fg=white,bright]#H %Y-%m-%d %H:%M:%S '
